{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "java-spring-auth-service-claude.serviceAccountName" . }}
  namespace: {{ include "java-spring-auth-service-claude.namespace" . }}
  labels:
    {{- include "java-spring-auth-service-claude.labels" . | nindent 4 }}
{{- end }}
